INSERT INTO job VALUES (1, '');
INSERT INTO class VALUES (2,'Füüsika II', 'Proin sed bibendum felis. Lorem ipsum dolor sit amet, consectetur adipiscing elit.', 'Viktor Malk', '90');
INSERT INTO class VALUES (3,'Matemaatiline analüüs', 'Quisque eleifend vulputate tempus. Nunc orci nisl, vulputate in mauris eget, lacinia iaculis arcu. Ut eu volutpat neque.', 'Endrik Kangur', '30');
INSERT INTO class VALUES (4,'Lineaaralgebra', 'Maecenas ac sagittis lacus. Donec vehicula tincidunt eros id fringilla.', 'Kaspar Laas', '60');
INSERT INTO class VALUES (5,'Psühholoogia', 'Nulla egestas mauris id interdum volutpat. Aliquam et gravida augue. ', 'Juri Parn', '60');
INSERT INTO class VALUES (6,'Filosoofia', 'Aenean dui est, pulvinar nec laoreet sit amet, posuere at ante. ', 'Enn Laas', '60');
INSERT INTO class VALUES (7,'Geograafia I', 'Phasellus fermentum pharetra metus, ac ultrices libero ornare ac.', 'Riho Sisask', '120');
INSERT INTO class VALUES (8,'Geograafia II', 'Praesent dapibus dui vitae massa fringilla molestie. Sed sed elit ut nisl pellentesque blandit nec luctus erat.', 'Albert Kangro', '180');
INSERT INTO class VALUES (9,'Inglise keel', 'Aliquam erat volutpat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. ', 'Anti Paasuke', '60');
INSERT INTO class VALUES (10,'Vene keel', 'Aliquam consequat rhoncus eleifend. Fusce sagittis at sem eget maximus. Pellentesque vel interdum ex.', 'Gustav Kuusk', '60');
INSERT INTO class VALUES (11,'Õigusteadus', 'Praesent facilisis, ex vel hendrerit consequat, massa dui tempus diam, quis tempor enim eros nec mauris.', 'Eliisa Puusepp', '60');
INSERT INTO class VALUES (12,'Keemia', 'Integer viverra molestie aliquet. Sed lacus libero, posuere tempor feugiat ut, suscipit eget est.', 'Kaili Levandi', '30');
INSERT INTO class VALUES (13,'Veebirakendused', 'Phasellus a elit sit amet sapien efficitur tristique vitae at dolor.', 'Karolin Kask', '90');
INSERT INTO class VALUES (14,'Kirjandus', 'Proin euismod cursus dui, sed aliquet urna iaculis id.', 'Hedi Nurmsalu', '60');
INSERT INTO class VALUES (15,'Elektroonika ', 'Ut pellentesque, elit volutpat ultricies efficitur, odio ligula congue odio, nec rutrum nisl velit a nisl.', 'Taimi Keskula', '120');
INSERT INTO class VALUES (16,'Geoloogia', 'Maecenas vel convallis elit, quis hendrerit nibh. Phasellus tincidunt vehicula nulla, non finibus arcu egestas vitae. ', 'Vilja Eenpalu', '120');
INSERT INTO class VALUES (17,'Majandus', 'Suspendisse bibendum cursus facilisis. Cras commodo erat mi.', 'Lembi Jogi', '60');
INSERT INTO class VALUES (18,'Arvutivõrgud', 'Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. In tempus tortor erat.', 'Merike Mark', '90');
INSERT INTO class VALUES (19,'Programmeerimine I', 'Maecenas odio augue, bibendum ac malesuada quis, ullamcorper nec velit. ', 'Anu Kapp', '60');
INSERT INTO class VALUES (20,'Programmeerimine II', 'Nullam elementum sapien et congue condimentum.', 'Elis Kirsipuu', '60');