ALTER TABLE WorkHour ALTER COLUMN title TYPE VARCHAR(255);
ALTER TABLE WorkHour ALTER COLUMN email TYPE VARCHAR(255);
ALTER TABLE WorkHour ALTER COLUMN end_time TYPE VARCHAR(255);
ALTER TABLE WorkHour ALTER COLUMN start_time TYPE VARCHAR(255);
ALTER TABLE WorkHour ALTER COLUMN created_at TYPE VARCHAR(255);
ALTER TABLE WorkHour ALTER COLUMN updated_at TYPE VARCHAR(255);